Game status and slice
2208-Capstone-Team-2/codenames pull request #46
Opened 2023-01-19 16:03 UTC by ocjarman

This is a pretty big PR.
It touches the flow of the game, updating gamestatus and remaining cards for each team on firebase and redux.

There are some simpler UI changes i.e. 'welcome, username' and 'whos turn it is' on the top of room view

There are also 4 functions critical to the game process: start game, end turn, submit clue, submit answer

on the roomview, whenever there is a change in the 'gameRef', the gamestatus and cards remaining are pulled from firebase to trigger certain actions on the front end

looking forward to going over this and discussing with everyone!

2023-01-19 17:28 UTC, rosalie0 requested changes
plan to refactor

2023-01-19 18:04 UTC, ocjarman commented on src/components/RoomView/Board.jsx
> +    if (gameStatus === 'team1OpsTurn' && Object.keys(teamOneOps).includes(playerId)) {
updated! might be cleaner way than pushing ids into an array and checking for playerId but wanted to have something up for team to see later

2023-01-20 16:46 UTC, Joshowens16 requested changes
Everything looks good, the only things that need be changed are:

1. useState needs to be imported in RoomView
2. on line 87 in RoomView, "playersNestedInRoom" should be "playersNestedInRoomRef"
3. useDispatch in setupGame needs to be imported, although I don't think its being used so you might be able to just remove it. Up to you!

2023-01-20 16:46 UTC, Joshowens16 commented on src/components/RoomView/RoomView.jsx
> +  const [loading, setLoading] = useState(false);
useState needs to be imported

2023-01-20 16:46 UTC, Joshowens16 commented on src/components/RoomView/RoomView.jsx
> +    onValue(playerNestedInRoom, (snapshot) => {
should be "playersNestedInRoomRef"

2023-01-20 16:46 UTC, Joshowens16 commented on src/components/RoomView/setupGame.jsx
> +  const dispatch = useDispatch();
useDispatch is not imported, dispatch seems to not be in use in this file so perhaps you could just remove line 13!

2023-01-20 16:46 UTC, Joshowens16 commented on src/store/index.js
>  import playerReducer from './playerSlice';
redux looks good!

2023-01-20 16:58 UTC, Joshowens16 approved these changes
looks good!

2023-01-20 17:00 UTC, rosalie0 approved these changes

2023-01-20 17:00 UTC, merged

2023-01-20 17:01 UTC, rosalie0 commented on src/components/RoomView/Card.jsx
> +const Card = ({singleWord, value, submitAnswer}) => {
IGNORE THIS! it was on an old commit and i realized i hadn't finalized my review so it was just sitting there